server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendai_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Aanand@2006
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update   
    show-sql: true
    generate-ddl: true 

jwt:
  secret: bXlTZWNyZXRLZXlUaGF0SXNMb25nRW5vdWdoRm9ySFM1MTJBbGdvcml0aG0xMjM0NTY3ODkwYWJjZGVmZ2hpams=
  expiration: 86400000
